package com.atlassian.selenium;

import com.atlassian.performance.junit.PerformanceListener;
import com.atlassian.performance.PerformanceReporter;
import junit.framework.*;

import java.io.File;
import java.io.IOException;

/**
 * A skeleton test suite for Selenium tests. The run method starts the selenium server (if the
 * selenium configuration class has been set to allow this.
 *
 * @since v3.12
 */
public abstract class SeleniumTestSuite extends TestSuite
{

    /**
     * To be implemented by users of this class.
     * @return an implementation of the SeleniumConfiguration interface containing the appropriate
     * selenium configuration information.
     */
    protected abstract SeleniumConfiguration getSeleniumConfiguration();


    /**
     * A special run methods that, depending on the SeleniumConfiguration, will start the selenium
     * server and client.
     * @param testResult Test results class to be passed to parent
     */
    public final void run(TestResult testResult)
    {
        SeleniumConfiguration config = getSeleniumConfiguration();

        SeleniumStarter.getInstance().start(config);
        SeleniumStarter.getInstance().setManual(false);

        PerformanceReporter reporter = new PerformanceReporter();

        testResult.addListener(new PerformanceListener(reporter));

        super.run(testResult);

        SeleniumStarter.getInstance().stop();

        if(config.getPerformanceReportLocation() != null)
        {
            System.out.println("SeleniumTestSuite.run log file = " + config.getPerformanceReportLocation());
            File reportFile = new File(config.getPerformanceReportLocation());
            try
            {
                reporter.writeReport(reportFile, config.getShowAutoGeneratedPerformanceEvents());
            }
            catch(IOException ioe)
            {
                throw new RuntimeException("Unable to write performance log file: " + reportFile, ioe);
            }
        }

    }


}
