package com.atlassian.pageobjects.elements.test.pageobjects.component;

import com.atlassian.pageobjects.PageBinder;
import com.atlassian.pageobjects.binder.Init;
import com.atlassian.pageobjects.components.ActivatedComponent;
import com.atlassian.pageobjects.components.aui.AuiInlineDialog;
import com.atlassian.pageobjects.elements.PageElement;
import com.atlassian.webdriver.AtlassianWebDriver;
import org.openqa.selenium.By;

import javax.inject.Inject;

/**
 * Represents the inline dialog that is shown when clicking a link on the AuiPage. This page is generated by the
 * AUIServlet plugin that is installed in the RefApp
 */
public class InlineDialog implements ActivatedComponent<InlineDialog>
{
    @Inject
    private AtlassianWebDriver driver;

    @Inject
    private PageBinder pageBinder;

    private AuiInlineDialog dialog;

    @Init
    public void initialize()
    {
         dialog = pageBinder.bind(AuiInlineDialog.class, By.id("popupLink"), "1");
    }

    public String content()
    {
        return getView().find(By.id("dialog-content")).getText();
    }


    public PageElement getTrigger()
    {
        return dialog.getTrigger();
    }

    public PageElement getView()
    {
        return dialog.getView();
    }

    public InlineDialog open()
    {
        dialog.open();
        return this;
    }

    public boolean isOpen()
    {
        return dialog.isOpen();
    }
}