package com.atlassian.pageobjects.elements.test.pageobjects.component;

import com.atlassian.pageobjects.PageBinder;
import com.atlassian.pageobjects.binder.Init;
import com.atlassian.pageobjects.components.ActivatedComponent;
import com.atlassian.pageobjects.components.aui.AuiDropDownMenu;
import com.atlassian.pageobjects.elements.PageElement;
import com.atlassian.pageobjects.elements.test.pageobjects.page.JQueryPage;
import com.atlassian.webdriver.AtlassianWebDriver;
import org.openqa.selenium.By;

import javax.inject.Inject;
import java.util.List;

/**
 * Represents the Links menu that is present in the AUIPage. This page is generated by the AUIServlet plugin that is
 * installed in the RefApp
 */
public class LinksMenu implements ActivatedComponent<LinksMenu>
{
    @Inject
    private AtlassianWebDriver driver;

    @Inject
    private PageBinder pageBinder;

    private AuiDropDownMenu auiMenu;

    @Init
    public void initialize()
    {
        auiMenu = pageBinder.bind(AuiDropDownMenu.class, By.id("dropDown-standard"));
    }

    public PageElement getTrigger()
    {
        return auiMenu.getTrigger();
    }

    public PageElement getView()
    {
        return auiMenu.getView();
    }

    public LinksMenu open()
    {
        auiMenu.open();
        return this;
    }

    public LinksMenu close()
    {
        auiMenu.close();
        return this;
    }

    public boolean isOpen()
    {
        return auiMenu.isOpen();
    }

    public List<String> getItems()
    {
        return auiMenu.getItems();
    }

    public JQueryPage gotoJQueryPage()
    {
        getView().find(By.linkText("JQuery Page")).click();
        return pageBinder.bind(JQueryPage.class);
    }
}
